---
title: "Scratch_Work"
author: "Matt Johnson"
date: "8/25/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(gridExtra)
```

```{r}
combine <- read.csv("source_data/combine.csv")
draft <- read.csv("source_data/draft.csv")
```

```{r}
# head(combine)
# str(combine)
# summary(combine)
```

```{r}
# head(draft)
# str(draft)
# summary(draft)
```


Initial cleaning
```{r}
#I'm thinking i'm going to use only data from 2000 on. I think these observations will be more complete. Also since the game has changed so much, this sort of analysis is only really relevant in the modern era of football. I also do not need a lot of these variables, lets select important ones 
Comb.2000 <- combine %>% 
  filter(combineYear >= 2000) %>% 
  select(1:6, 8:18, 28:33)
Draft.2000 <- draft %>% 
  filter(draft >= 2000) %>% 
  select(1:19)
  
#ok lets take out any rows with an NA just to see
Comb.compl <- na.omit(Comb.2000) 
Draft.compl <- na.omit(Draft.2000)[, c(1, 3, 4)]
```

Join and make final single csv

```{r}
#join
DF.clean <- na.omit(left_join(Comb.compl, Draft.compl, by = "playerId")[, -c(1, 3, 4:9, 11:13, 16)])
DF.clean$position <- factor(DF.clean$position)
```

I think I need to split into positions to really see what's up
```{r}
#Lets fist split into offense and defense and then split more from there
DF.Off.skill <- DF.clean %>% 
  filter(position == "WR" | position == "RB" | position == "TE")
DF.Off.strength <- DF.clean %>% 
  filter(position == "C" | position == "OG" | position == "OT" | position == "OL")
DF.Def.skill <- DF.clean %>% 
  filter(position == "DB" | position == "S")
DF.Def.strength <- DF.clean %>% 
  filter(position == "DE" | position == "DL" | position == "DT" | position == "LB" | position == "OLB")
```

Graphs
```{r}
g1 <- ggplot(DF.Off.skill, mapping = aes(x = combine40yd, y = pick, color = position)) +     geom_point(alpha = .5) +
  xlab("40 Time") +
  ylab("Pick") +
  labs(color = "Position", title = "Offense") +
  xlim(4, 5.2) +
  theme(legend.position = c(0, 1),
                  legend.justification = c(0, 1))

g2 <- ggplot(DF.Off.strength, mapping = aes(x = combineBench, y = pick, color = position)) +     geom_point(alpha = .5) +
  xlab("Benchpress") +
  ylab("Pick") +
  labs(color = "Position")

g3 <- ggplot(DF.Def.skill, mapping = aes(x = combine40yd, y = pick, color = position)) +     geom_point(alpha = .5) +
  xlab("40 Time") +
  ylab("Pick") +
  labs(color = "Position", title = "Defense") +
  xlim(4, 5.2) +
  theme(legend.position = c(0, 1),
                  legend.justification = c(0, 1))

g4 <- ggplot(DF.Def.strength, mapping = aes(x = combineBench, y = pick, color = position)) +     geom_point(alpha = .5) +
  xlab("Benchpress") +
  ylab("Pick") +
  labs(color = "Position")

g2
g4
```

```{r}
Graph1 <- grid.arrange(g1, g3, nrow=1)
ggsave("derived_graphs/Off.Def.40s.png", plot = Graph1)
```

weights
```{r}
g5 <- ggplot(DF.Off.skill, aes(weight)) +
  geom_density(aes(color=position), alpha=.5) +
  xlim(170, 400) +
  xlab("Weights") +
  ylab("") +
  labs(color="Position") +
   theme(legend.position = c(0, 1),
                  legend.justification = c(0, 1))
#g5

g6 <- ggplot(DF.Off.strength, aes(weight)) +
  geom_density(aes(color=position), alpha=.5) +
  xlim(170,400) +
  xlab("Weights") +
  ylab("") +
  labs(color="Position") +
   theme(legend.position = c(0, 1),
                  legend.justification = c(0, 1))
#g6

Graph2 <- grid.arrange(g5, g6, nrow=1, top = "Weight Distribution by Position (Offense)")
```

```{r}
g7 <- ggplot(DF.Off.skill, aes(ageAtDraft)) +
  geom_histogram(aes(fill = position), position = "dodge") +
  xlab("Age at Draft") +
  ylab("Count") +
  labs(fill = "Position", title = "Offense Skill") +
  theme(legend.position = c(0, 1),
        legend.justification = c(0, 1),
        legend.key.size = unit(.25, "cm")) +
  theme(axis.text.y=element_blank())
#g7

g8 <- ggplot(DF.Off.strength, aes(ageAtDraft)) +
  geom_histogram(aes(fill = position), position = "dodge") +
  xlab("Age at Draft") +
  ylab("Count") +
  labs(fill = "Position", title = "Offense Line") +
  theme(legend.position = c(0, 1),
        legend.justification = c(0, 1),
        legend.key.size = unit(.25, "cm")) +
  theme(axis.text.y=element_blank())
#g8

g9 <- ggplot(DF.Def.skill, aes(ageAtDraft)) +
  geom_histogram(aes(fill = position), position = "dodge") +
  xlab("Age at Draft") +
  ylab("Count") +
  labs(fill = "Position", title = "Defense Skill") +
  theme(legend.position = c(0, 1),
        legend.justification = c(0, 1),
        legend.key.size = unit(.25, "cm")) +
  theme(axis.text.y=element_blank())
#g9

g10 <- ggplot(DF.Def.strength, aes(ageAtDraft)) +
  geom_histogram(aes(fill = position), position = "dodge") +
  xlab("Age at Draft") +
  ylab("Count") +
  labs(fill = "Position", title = "Defense Line") +
  theme(legend.position = c(0, 1),
        legend.justification = c(0, 1),
        legend.key.size = unit(.25, "cm")) +
  theme(axis.text.y=element_blank())
#g10

Graphs3 <- grid.arrange(g7, g8, g9, g10, nrow=2, top = "Age Distribution by Position")
```








